-- SIGE-RUTH baseline security migration.
-- Apply from Supabase SQL Editor with an owner/service role account.

create extension if not exists pgcrypto;

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  nombre text not null,
  rol text not null check (rol in ('director', 'secretaria', 'docente', 'fonoaudiologo', 'jefe_utp')),
  activo boolean not null default true,
  sede_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.cursos (
  id text primary key,
  nombre text not null,
  nivel text not null,
  profesor_jefe text,
  sede_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.estudiantes (
  id bigint generated by default as identity primary key,
  rut text not null,
  nombre text not null,
  apellido_paterno text not null,
  apellido_materno text,
  fecha_nacimiento date,
  diagnostico text check (diagnostico is null or diagnostico in ('TEL Mixto', 'TEL Expresivo')),
  nivel text not null check (nivel in ('Medio Mayor', 'NT1', 'NT2')),
  jornada text check (jornada is null or jornada in ('Mañana', 'Tarde')),
  anamnesis boolean not null default false,
  prueba_inicial boolean not null default false,
  nombre_apoderado text,
  telefono_apoderado text,
  activo boolean not null default true,
  sede_id text not null,
  curso_id text references public.cursos(id) on update cascade on delete set null,
  created_at timestamptz not null default now()
);

create unique index if not exists estudiantes_rut_unique
  on public.estudiantes (rut);
create index if not exists estudiantes_sede_activo_idx
  on public.estudiantes (sede_id, activo);
create index if not exists estudiantes_curso_idx
  on public.estudiantes (curso_id);

create table if not exists public.asistencia (
  id bigint generated by default as identity primary key,
  estudiante_id bigint not null references public.estudiantes(id) on delete cascade,
  fecha date not null,
  estado text not null check (estado in ('P', 'A', 'J')),
  observacion text,
  registrado_por uuid references public.perfiles(id) on delete set null,
  cerrada boolean not null default false,
  sede_id text not null,
  created_at timestamptz not null default now(),
  unique (estudiante_id, fecha)
);

create index if not exists asistencia_sede_fecha_idx
  on public.asistencia (sede_id, fecha);

create table if not exists public.sesiones_fono (
  id bigint generated by default as identity primary key,
  fecha date not null,
  estudiante_id bigint not null references public.estudiantes(id) on delete cascade,
  fonoaudiologo_id uuid not null references public.perfiles(id) on delete restrict,
  actividad_realizada text not null,
  observaciones text,
  nivel_fonetico integer not null check (nivel_fonetico between 1 and 3),
  nivel_semantico integer not null check (nivel_semantico between 1 and 3),
  nivel_morfosintactico integer not null check (nivel_morfosintactico between 1 and 3),
  nivel_pragmatico integer not null check (nivel_pragmatico between 1 and 3),
  sede_id text not null,
  created_at timestamptz not null default now()
);

create index if not exists sesiones_fono_sede_fecha_idx
  on public.sesiones_fono (sede_id, fecha desc);
create index if not exists sesiones_fono_estudiante_idx
  on public.sesiones_fono (estudiante_id, fecha desc);

create table if not exists public.estudiantes_documentos (
  id uuid primary key default gen_random_uuid(),
  estudiante_id bigint not null references public.estudiantes(id) on delete cascade,
  nombre_archivo text not null,
  url_archivo text not null,
  subido_por uuid references public.perfiles(id) on delete set null,
  sede_id text not null,
  created_at timestamptz not null default now()
);

create index if not exists estudiantes_documentos_estudiante_idx
  on public.estudiantes_documentos (estudiante_id, created_at desc);

create table if not exists public.auditoria (
  id bigint generated by default as identity primary key,
  accion text not null,
  entidad text not null,
  entidad_id text,
  usuario_id uuid references public.perfiles(id) on delete set null,
  valor_anterior jsonb,
  valor_nuevo jsonb,
  sede_id text,
  created_at timestamptz not null default now()
);

create index if not exists auditoria_sede_created_idx
  on public.auditoria (sede_id, created_at desc);

create or replace function public.audit_row_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  action_name text;
  row_id text;
  row_sede text;
begin
  action_name := case tg_op
    when 'INSERT' then 'CREAR'
    when 'UPDATE' then 'MODIFICAR'
    when 'DELETE' then 'ELIMINAR'
  end;

  row_id := coalesce((to_jsonb(new)->>'id'), (to_jsonb(old)->>'id'));
  row_sede := coalesce((to_jsonb(new)->>'sede_id'), (to_jsonb(old)->>'sede_id'));

  insert into public.auditoria (
    accion,
    entidad,
    entidad_id,
    usuario_id,
    valor_anterior,
    valor_nuevo,
    sede_id
  )
  values (
    action_name,
    tg_table_name,
    row_id,
    auth.uid(),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end,
    row_sede
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists audit_estudiantes on public.estudiantes;
create trigger audit_estudiantes
after insert or update or delete on public.estudiantes
for each row execute function public.audit_row_changes();

drop trigger if exists audit_asistencia on public.asistencia;
create trigger audit_asistencia
after insert or update or delete on public.asistencia
for each row execute function public.audit_row_changes();

drop trigger if exists audit_sesiones_fono on public.sesiones_fono;
create trigger audit_sesiones_fono
after insert or update or delete on public.sesiones_fono
for each row execute function public.audit_row_changes();

drop trigger if exists audit_estudiantes_documentos on public.estudiantes_documentos;
create trigger audit_estudiantes_documentos
after insert or update or delete on public.estudiantes_documentos
for each row execute function public.audit_row_changes();

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.rol::text
  from public.perfiles p
  where p.id = auth.uid()
    and p.activo = true
  limit 1
$$;

create or replace function public.current_profile_sede()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.sede_id::text
  from public.perfiles p
  where p.id = auth.uid()
    and p.activo = true
  limit 1
$$;

create or replace function public.has_role(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_profile_role() = any(allowed_roles), false)
$$;

create or replace function public.can_access_sede(target_sede text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.has_role(array['director', 'jefe_utp'])
    or public.current_profile_sede() = target_sede,
    false
  )
$$;

alter table if exists public.perfiles enable row level security;
alter table if exists public.estudiantes enable row level security;
alter table if exists public.asistencia enable row level security;
alter table if exists public.sesiones_fono enable row level security;
alter table if exists public.estudiantes_documentos enable row level security;
alter table if exists public.auditoria enable row level security;
alter table if exists public.cursos enable row level security;

drop policy if exists perfiles_select on public.perfiles;
create policy perfiles_select on public.perfiles
for select to authenticated
using (
  id = auth.uid()
  or public.has_role(array['director', 'jefe_utp'])
  or public.can_access_sede(sede_id::text)
);

drop policy if exists perfiles_update_director on public.perfiles;
create policy perfiles_update_director on public.perfiles
for update to authenticated
using (public.has_role(array['director']))
with check (public.has_role(array['director']));

drop policy if exists estudiantes_select on public.estudiantes;
create policy estudiantes_select on public.estudiantes
for select to authenticated
using (public.can_access_sede(sede_id::text));

drop policy if exists estudiantes_insert on public.estudiantes;
create policy estudiantes_insert on public.estudiantes
for insert to authenticated
with check (
  public.has_role(array['director', 'secretaria'])
  and public.can_access_sede(sede_id::text)
);

drop policy if exists estudiantes_update on public.estudiantes;
create policy estudiantes_update on public.estudiantes
for update to authenticated
using (
  public.has_role(array['director', 'secretaria', 'jefe_utp'])
  and public.can_access_sede(sede_id::text)
)
with check (
  public.has_role(array['director', 'secretaria', 'jefe_utp'])
  and public.can_access_sede(sede_id::text)
);

drop policy if exists estudiantes_delete_director on public.estudiantes;
create policy estudiantes_delete_director on public.estudiantes
for delete to authenticated
using (public.has_role(array['director']));

drop policy if exists asistencia_select on public.asistencia;
create policy asistencia_select on public.asistencia
for select to authenticated
using (public.can_access_sede(sede_id::text));

drop policy if exists asistencia_insert on public.asistencia;
create policy asistencia_insert on public.asistencia
for insert to authenticated
with check (
  public.has_role(array['director', 'docente', 'fonoaudiologo', 'jefe_utp'])
  and public.can_access_sede(sede_id::text)
);

drop policy if exists asistencia_update on public.asistencia;
create policy asistencia_update on public.asistencia
for update to authenticated
using (
  public.can_access_sede(sede_id::text)
  and (
    public.has_role(array['director', 'jefe_utp'])
    or (public.has_role(array['docente', 'fonoaudiologo']) and cerrada = false)
  )
)
with check (
  public.can_access_sede(sede_id::text)
  and public.has_role(array['director', 'docente', 'fonoaudiologo', 'jefe_utp'])
);

drop policy if exists sesiones_fono_select on public.sesiones_fono;
create policy sesiones_fono_select on public.sesiones_fono
for select to authenticated
using (public.can_access_sede(sede_id::text));

drop policy if exists sesiones_fono_write on public.sesiones_fono;
create policy sesiones_fono_write on public.sesiones_fono
for all to authenticated
using (
  public.has_role(array['director', 'fonoaudiologo', 'jefe_utp'])
  and public.can_access_sede(sede_id::text)
)
with check (
  public.has_role(array['director', 'fonoaudiologo', 'jefe_utp'])
  and public.can_access_sede(sede_id::text)
);

drop policy if exists documentos_select on public.estudiantes_documentos;
create policy documentos_select on public.estudiantes_documentos
for select to authenticated
using (public.can_access_sede(sede_id::text));

drop policy if exists documentos_insert on public.estudiantes_documentos;
create policy documentos_insert on public.estudiantes_documentos
for insert to authenticated
with check (
  public.has_role(array['director', 'secretaria', 'fonoaudiologo', 'jefe_utp'])
  and public.can_access_sede(sede_id::text)
);

drop policy if exists documentos_delete on public.estudiantes_documentos;
create policy documentos_delete on public.estudiantes_documentos
for delete to authenticated
using (
  public.has_role(array['director', 'secretaria', 'jefe_utp'])
  and public.can_access_sede(sede_id::text)
);

drop policy if exists auditoria_select on public.auditoria;
create policy auditoria_select on public.auditoria
for select to authenticated
using (
  public.has_role(array['director', 'fonoaudiologo', 'jefe_utp'])
  and public.can_access_sede(sede_id::text)
);

drop policy if exists cursos_select on public.cursos;
create policy cursos_select on public.cursos
for select to authenticated
using (public.can_access_sede(sede_id::text));

drop policy if exists cursos_write_director on public.cursos;
create policy cursos_write_director on public.cursos
for all to authenticated
using (
  public.has_role(array['director'])
  and public.can_access_sede(sede_id::text)
)
with check (
  public.has_role(array['director'])
  and public.can_access_sede(sede_id::text)
);

insert into storage.buckets (id, name, public)
values ('documentos_estudiantes', 'documentos_estudiantes', false)
on conflict (id) do update set public = false;

drop policy if exists documentos_storage_select on storage.objects;
create policy documentos_storage_select on storage.objects
for select to authenticated
using (
  bucket_id = 'documentos_estudiantes'
  and exists (
    select 1
    from public.estudiantes e
    where e.id::text = (storage.foldername(name))[1]
      and public.can_access_sede(e.sede_id::text)
  )
);

drop policy if exists documentos_storage_insert on storage.objects;
create policy documentos_storage_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'documentos_estudiantes'
  and public.has_role(array['director', 'secretaria', 'fonoaudiologo', 'jefe_utp'])
  and exists (
    select 1
    from public.estudiantes e
    where e.id::text = (storage.foldername(name))[1]
      and public.can_access_sede(e.sede_id::text)
  )
);

drop policy if exists documentos_storage_delete on storage.objects;
create policy documentos_storage_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'documentos_estudiantes'
  and public.has_role(array['director', 'secretaria', 'jefe_utp'])
  and exists (
    select 1
    from public.estudiantes e
    where e.id::text = (storage.foldername(name))[1]
      and public.can_access_sede(e.sede_id::text)
  )
);
